-- This file is superseded by supabase/migrations/20260421120000_split_app_schema.sql
-- (progress_state now lives in the `geriatrics` schema, not `public`).
--
-- To apply the current schema, run:
--
--   supabase db push
--
-- ...or paste supabase/migrations/20260421120000_split_app_schema.sql into the
-- Supabase SQL Editor. Remember to add `geriatrics` to Project Settings ->
-- API -> Exposed schemas after applying.
