#!/usr/bin/env python3
"""
2020_al_fix.py — Apply c-value fixes for 2020_al.

Exam: 2020_al (al / 2020)
Answer source: IMA revised answer key
Confidence: sim >= 0.90, single accepted answer.

Generated by scripts/exam_audit/generate_fixes.py from audit report.

Usage:
    python3 2020_al_fix.py              # dry run
    python3 2020_al_fix.py --apply      # write changes to questions.json
"""
import json, sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
QJ = REPO / 'data' / 'questions.json'

# Each entry: (q_num, idx, new_c, accepted_list, current_tag, similarity)
FIXES = [
    (  6,   767, 1, [1], '2023-ב', 0.97),
    (  9,   770, 0, [0], '2023-ב', 0.957),
    ( 12,   773, 1, [1], '2023-ב', 1.0),
    ( 15,   776, 2, [2], '2023-ב', 1.0),
    ( 16,   777, 2, [2], '2023-ב', 0.966),
    ( 17,   778, 1, [1], '2023-ב', 1.0),
    ( 19,   780, 1, [1], '2023-ב', 1.0),
    ( 20,   781, 0, [0], '2023-ב', 0.98),
    ( 21,   782, 3, [3], '2023-ב', 1.0),
    ( 23,   784, 3, [3], '2023-ב', 1.0),
    ( 26,   787, 3, [3], '2023-ב', 0.95),
    ( 28,   789, 2, [2], '2023-ב', 1.0),
    ( 31,   792, 2, [2], '2023-ב', 0.974),
    ( 32,   793, 2, [2], '2023-ב', 0.968),
    ( 35,   796, 1, [1], '2023-ב', 0.997),
    ( 37,   798, 0, [0], '2023-ב', 1.0),
    ( 38,   799, 1, [1], '2023-ב', 1.0),
    ( 39,   800, 2, [2], '2023-ב', 0.98),
    ( 45,   805, 0, [0], '2023-ב', 1.0),
    ( 48,   807, 1, [1], '2023-ב', 0.973),
    ( 53,   812, 0, [0], '2023-ב', 0.97),
    ( 57,   816, 1, [1], '2023-ב', 0.937),
    ( 59,   818, 3, [3], '2023-ב', 0.939),
    ( 60,   819, 2, [2], '2023-ב', 1.0),
    ( 62,   821, 0, [0], '2023-ב', 0.999),
    ( 65,   824, 2, [2], '2023-ב', 1.0),
    ( 67,   826, 1, [1], '2023-ב', 1.0),
    ( 68,   827, 2, [2], '2023-ב', 0.926),
    ( 69,   828, 1, [1], '2023-ב', 1.0),
    ( 71,   830, 0, [0], '2023-ב', 0.98),
    ( 72,   831, 1, [1], '2023-ב', 0.993),
    ( 76,   834, 3, [3], '2023-ב', 0.967),
    ( 79,   837, 1, [1], '2023-ב', 1.0),
    ( 80,   838, 1, [1], '2023-ב', 1.0),
    ( 81,   839, 1, [1], '2023-ב', 1.0),
    ( 82,   840, 2, [2], '2023-ב', 0.949),
    ( 83,   841, 1, [1], '2023-ב', 1.0),
    ( 84,   842, 0, [0], '2023-ב', 0.995),
    ( 85,   843, 1, [1], '2023-ב', 0.967),
    ( 86,   844, 2, [2], '2023-ב', 1.0),
    ( 93,   851, 2, [2], '2023-ב', 1.0),
    ( 94,   852, 2, [2], '2023-ב', 0.924),
    ( 99,   857, 2, [2], '2023-ב', 1.0),
]

def main():
    apply = '--apply' in sys.argv
    with open(QJ) as f: qs = json.load(f)
    changed = 0
    for q_num, idx, new_c, accepted, cur_tag, sim in FIXES:
        q = qs[idx]
        cur_c = q.get('c')
        if cur_c in accepted:
            continue  # already valid
        print(f'  Q{q_num}: idx={idx} tag={cur_tag!r} c={cur_c} → {new_c} (sim {sim})')
        if apply:
            qs[idx]['c'] = new_c
            changed += 1
    print(f'\nTotal fixes in script: {len(FIXES)}')
    if apply:
        print(f'Applied: {changed}')
        with open(QJ, 'w') as f: json.dump(qs, f, ensure_ascii=False, indent=1)
    else:
        print('DRY RUN — use --apply to write changes')

if __name__ == '__main__':
    main()
