#!/usr/bin/env python3
"""
2021_al_fix.py — Apply c-value fixes for 2021_al.

Exam: 2021_al (al / 2021)
Answer source: IMA revised answer key
Confidence: sim >= 0.90, single accepted answer.

Generated by scripts/exam_audit/generate_fixes.py from audit report.

Usage:
    python3 2021_al_fix.py              # dry run
    python3 2021_al_fix.py --apply      # write changes to questions.json
"""
import json, sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent.parent
QJ = REPO / 'data' / 'questions.json'

# Each entry: (q_num, idx, new_c, accepted_list, current_tag, similarity)
FIXES = [
    (  2,   860, 2, [2], 'יוני 21', 1.0),
    ( 61,   912, 3, [3], 'יוני 21', 0.935),
]

def main():
    apply = '--apply' in sys.argv
    with open(QJ) as f: qs = json.load(f)
    changed = 0
    for q_num, idx, new_c, accepted, cur_tag, sim in FIXES:
        q = qs[idx]
        cur_c = q.get('c')
        if cur_c in accepted:
            continue  # already valid
        print(f'  Q{q_num}: idx={idx} tag={cur_tag!r} c={cur_c} → {new_c} (sim {sim})')
        if apply:
            qs[idx]['c'] = new_c
            changed += 1
    print(f'\nTotal fixes in script: {len(FIXES)}')
    if apply:
        print(f'Applied: {changed}')
        with open(QJ, 'w') as f: json.dump(qs, f, ensure_ascii=False, indent=1)
    else:
        print('DRY RUN — use --apply to write changes')

if __name__ == '__main__':
    main()
