#!/usr/bin/env python3
"""
2021_al_fix.py — Apply c-value fixes for 2021_al.

Exam: 2021_al (al / 2021)
Answer source: IMA revised answer key
Confidence: sim >= 0.90, single accepted answer.

Generated by scripts/exam_audit/generate_fixes.py from audit report.

Usage:
    python3 2021_al_fix.py              # dry run
    python3 2021_al_fix.py --apply      # write changes to questions.json
"""
import json, sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
QJ = REPO / 'data' / 'questions.json'

# Each entry: (q_num, idx, new_c, accepted_list, current_tag, similarity)
FIXES = [
    (  8,   866, 3, [3], '2023-ב', 1.0),
    ( 12,   869, 2, [2], '2023-ב', 1.0),
    ( 13,   870, 0, [0], '2023-ב', 0.93),
    ( 15,   872, 2, [2], '2023-ב', 1.0),
    ( 16,   873, 0, [0], '2023-ב', 1.0),
    ( 17,   874, 3, [3], '2023-ב', 0.934),
    ( 25,   881, 2, [2], '2023-ב', 1.0),
    ( 28,   884, 2, [2], '2023-ב', 0.924),
    ( 30,   885, 2, [2], '2023-ב', 1.0),
    ( 34,   889, 3, [3], '2023-ב', 0.95),
    ( 39,   893, 3, [3], '2023-ב', 1.0),
    ( 42,   895, 2, [2], '2023-ב', 1.0),
    ( 43,   896, 2, [2], '2023-ב', 0.946),
    ( 46,   897, 1, [1], '2023-ב', 1.0),
    ( 47,   898, 3, [3], '2023-ב', 1.0),
    ( 48,   899, 0, [0], '2023-ב', 0.913),
    ( 50,   901, 1, [1], '2023-ב', 1.0),
    ( 51,   902, 0, [0], '2023-ב', 0.953),
    ( 52,   903, 0, [0], '2023-ב', 1.0),
    ( 56,   907, 1, [1], '2023-ב', 1.0),
    ( 57,   908, 0, [0], '2023-ב', 1.0),
    ( 58,   909, 1, [1], '2023-ב', 0.962),
    ( 60,   911, 0, [0], '2023-ב', 1.0),
    ( 64,   915, 2, [2], '2023-ב', 1.0),
    ( 69,   918, 3, [3], '2023-ב', 1.0),
    ( 70,   919, 2, [2], '2023-ב', 1.0),
    ( 71,   920, 0, [0], '2023-ב', 1.0),
    ( 72,   921, 2, [2], '2023-ב', 0.952),
    ( 75,   923, 0, [0], '2023-ב', 0.909),
    ( 77,   924, 3, [3], '2023-ב', 1.0),
    ( 78,   925, 0, [0], '2023-ב', 0.922),
    ( 80,   927, 1, [1], '2023-ב', 0.996),
    ( 81,   928, 2, [2], '2023-ב', 0.903),
    ( 82,   929, 1, [1], '2023-ב', 0.993),
    ( 84,   931, 1, [1], '2023-ב', 1.0),
    ( 86,   933, 2, [2], '2023-ב', 0.902),
    ( 88,   935, 3, [3], '2023-ב', 0.945),
    ( 89,   936, 2, [2], '2023-ב', 1.0),
    ( 91,   938, 3, [3], '2023-ב', 0.909),
    ( 93,   940, 0, [0], '2023-ב', 1.0),
    ( 95,   942, 2, [2], '2023-ב', 1.0),
    ( 98,   945, 2, [2], '2023-ב', 1.0),
    ( 99,   946, 0, [0], '2023-ב', 1.0),
    (100,   947, 1, [1], '2023-ב', 1.0),
]

def main():
    apply = '--apply' in sys.argv
    with open(QJ) as f: qs = json.load(f)
    changed = 0
    for q_num, idx, new_c, accepted, cur_tag, sim in FIXES:
        q = qs[idx]
        cur_c = q.get('c')
        if cur_c in accepted:
            continue  # already valid
        print(f'  Q{q_num}: idx={idx} tag={cur_tag!r} c={cur_c} → {new_c} (sim {sim})')
        if apply:
            qs[idx]['c'] = new_c
            changed += 1
    print(f'\nTotal fixes in script: {len(FIXES)}')
    if apply:
        print(f'Applied: {changed}')
        with open(QJ, 'w') as f: json.dump(qs, f, ensure_ascii=False, indent=1)
    else:
        print('DRY RUN — use --apply to write changes')

if __name__ == '__main__':
    main()
