#!/usr/bin/env python3
"""
2025_al_fix.py — Apply c-value fixes for 2025_al.

Exam: 2025_al (al / 2025)
Answer source: IMA revised answer key
Confidence: sim >= 0.90, single accepted answer.

Generated by scripts/exam_audit/generate_fixes.py from audit report.

Usage:
    python3 2025_al_fix.py              # dry run
    python3 2025_al_fix.py --apply      # write changes to questions.json
"""
import json, sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
QJ = REPO / 'data' / 'questions.json'

# Each entry: (q_num, idx, new_c, accepted_list, current_tag, similarity)
FIXES = [
    (  6,   621, 3, [3], 'ספט 24', 1.0),
    ( 13,   628, 2, [2], 'ספט 24', 1.0),
    ( 14,   629, 0, [0], 'ספט 24', 1.0),
    ( 16,   631, 1, [1], 'ספט 24', 1.0),
    ( 19,   634, 3, [3], 'ספט 24', 0.963),
    ( 30,   645, 2, [2], 'ספט 24', 1.0),
    ( 43,   658, 2, [2], 'ספט 24', 1.0),
    ( 47,  1255, 3, [3], 'יוני 25', 0.935),
    ( 52,   667, 3, [3], 'ספט 24', 1.0),
    ( 54,   669, 0, [0], 'ספט 24', 1.0),
    ( 58,   673, 1, [1], 'ספט 24', 1.0),
    ( 61,   676, 0, [0], 'ספט 24', 0.998),
    ( 65,   680, 1, [1], 'ספט 24', 1.0),
    ( 71,   686, 0, [0], 'ספט 24', 1.0),
    ( 74,  1270, 1, [1], 'יוני 25', 0.998),
    ( 75,   690, 3, [3], 'ספט 24', 1.0),
    ( 78,   693, 2, [2], 'ספט 24', 1.0),
    ( 81,   695, 3, [3], 'ספט 24', 1.0),
    ( 84,  1275, 3, [3], 'יוני 25', 1.0),
    ( 85,   699, 2, [2], 'ספט 24', 0.952),
    ( 87,   701, 2, [2], 'ספט 24', 1.0),
    ( 94,  1281, 2, [2], 'יוני 25', 1.0),
    ( 96,  1283, 2, [2], 'יוני 25', 0.938),
    (100,   714, 3, [3], 'ספט 24', 1.0),
]

def main():
    apply = '--apply' in sys.argv
    with open(QJ) as f: qs = json.load(f)
    changed = 0
    for q_num, idx, new_c, accepted, cur_tag, sim in FIXES:
        q = qs[idx]
        cur_c = q.get('c')
        if cur_c in accepted:
            continue  # already valid
        print(f'  Q{q_num}: idx={idx} tag={cur_tag!r} c={cur_c} → {new_c} (sim {sim})')
        if apply:
            qs[idx]['c'] = new_c
            changed += 1
    print(f'\nTotal fixes in script: {len(FIXES)}')
    if apply:
        print(f'Applied: {changed}')
        with open(QJ, 'w') as f: json.dump(qs, f, ensure_ascii=False, indent=1)
    else:
        print('DRY RUN — use --apply to write changes')

if __name__ == '__main__':
    main()
