#!/usr/bin/env python3
"""
2025_basis_fix.py — Apply c-value fixes for 2025_basis.

Exam: 2025_basis (basis / 2025)
Answer source: IMA revised answer key
Confidence: sim >= 0.90, single accepted answer.

Generated by scripts/exam_audit/generate_fixes.py from audit report.

Usage:
    python3 2025_basis_fix.py              # dry run
    python3 2025_basis_fix.py --apply      # write changes to questions.json
"""
import json, sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent.parent
QJ = REPO / 'data' / 'questions.json'

# Each entry: (q_num, idx, new_c, accepted_list, current_tag, similarity)
FIXES = [
    (  1,   616, 3, [3], 'יוני 25', 1.0),
    (  4,   619, 0, [0], 'יוני 25', 0.951),
    ( 15,   630, 1, [1], 'יוני 25', 0.977),
    ( 21,   636, 0, [0], 'יוני 25', 0.942),
    ( 23,   638, 1, [1], 'יוני 25', 1.0),
    ( 26,   641, 3, [3], 'יוני 25', 1.0),
    ( 29,   644, 2, [2], 'יוני 25', 1.0),
    ( 31,   646, 1, [1], 'יוני 25', 1.0),
    ( 32,   647, 1, [1], 'יוני 25', 1.0),
    ( 34,   649, 0, [0], 'יוני 25', 0.97),
    ( 36,   651, 3, [3], 'יוני 25', 1.0),
    ( 38,   653, 0, [0], 'יוני 25', 1.0),
    ( 39,   654, 1, [1], 'יוני 25', 0.948),
    ( 44,   659, 0, [0], 'יוני 25', 1.0),
    ( 48,   663, 3, [3], 'יוני 25', 1.0),
    ( 50,   665, 3, [3], 'יוני 25', 1.0),
    ( 51,   666, 2, [2], 'יוני 25', 0.995),
    ( 63,   678, 0, [0], 'יוני 25', 1.0),
    ( 66,   681, 2, [2], 'יוני 25', 1.0),
    ( 68,   683, 0, [0], 'יוני 25', 1.0),
    ( 73,   688, 3, [3], 'יוני 25', 1.0),
    ( 76,   691, 1, [1], 'יוני 25', 1.0),
    ( 84,   698, 3, [3], 'יוני 25', 0.965),
    ( 90,   704, 3, [3], 'יוני 25', 1.0),
    ( 94,   708, 2, [2], 'יוני 25', 1.0),
    ( 98,   712, 0, [0], 'יוני 25', 1.0),
    ( 99,   713, 3, [3], 'יוני 25', 1.0),
    (101,   715, 1, [1], 'יוני 25', 1.0),
    (102,   716, 0, [0], 'יוני 25', 1.0),
    (114,   727, 2, [2], 'יוני 25', 0.938),
    (144,   755, 3, [3], 'יוני 25', 0.951),
    (146,   757, 2, [2], 'יוני 25', 1.0),
]

def main():
    apply = '--apply' in sys.argv
    with open(QJ) as f: qs = json.load(f)
    changed = 0
    for q_num, idx, new_c, accepted, cur_tag, sim in FIXES:
        q = qs[idx]
        cur_c = q.get('c')
        if cur_c in accepted:
            continue  # already valid
        print(f'  Q{q_num}: idx={idx} tag={cur_tag!r} c={cur_c} → {new_c} (sim {sim})')
        if apply:
            qs[idx]['c'] = new_c
            changed += 1
    print(f'\nTotal fixes in script: {len(FIXES)}')
    if apply:
        print(f'Applied: {changed}')
        with open(QJ, 'w') as f: json.dump(qs, f, ensure_ascii=False, indent=1)
    else:
        print('DRY RUN — use --apply to write changes')

if __name__ == '__main__':
    main()
