#!/usr/bin/env python3
"""
build_grs8_chapters.py — parse the GRS8 Book 3 topic index (page 11) + question
page anchors, emit data/grs8_chapters.json.

GRS8 Book 3 is a Q&A volume (333 case-oriented MCQs). Each "chapter" in our
model is a TOPIC (the same topic structure used in Book 1's syllabus chapters
and indexed on page 11 of Book 3). Pages = page range of all questions on
that topic.
"""
import json, os, sys

PDF = 'grs8_part01.pdf'
OUT = 'data/grs8_chapters.json'

# Q -> page from _q_pages.json (built earlier via ANSWER markers)
Q_PAGES = json.load(open('_q_pages.json', encoding='utf-8'))
Q_PAGES = {int(k): v for k, v in Q_PAGES.items()}

# GRS8 topic index (page 11) - hand-cleaned from OCR
GRS8_TOPICS = [
    ("Adverse Drug Events", [9, 24, 246, 269, 303]),
    ("Anxiety Disorders", [62, 173, 196, 214, 305]),
    ("Assessment", [46, 72, 97, 219, 237, 249, 313, 327]),
    ("Back and Neck Pain", [189, 270, 301, 325]),
    ("Behavior Problems in Dementia", [20, 28, 53, 212, 217, 245, 272]),
    ("Biology", [26, 247, 265, 266, 302]),
    ("Cardiovascular Diseases and Disorders", [3, 48, 95, 108, 114, 236, 256]),
    ("Community-Based Care", [117, 119, 125, 132, 138, 178, 254, 292]),
    ("Complementary and Alternative Medicine", [25, 58, 66, 77, 189, 205]),
    ("Cultural Aspects of Care", [13, 18, 82, 156, 317]),
    ("Delirium", [1, 32, 39, 154, 158, 293, 321]),
    ("Dementia", [4, 28, 110, 120, 130, 154, 217, 226, 272, 278, 283, 299, 313]),
    ("Demography", [37, 143, 179, 273]),
    ("Depression and Other Mood Disorders", [20, 68, 72, 103, 182, 190, 235, 244, 249]),
    ("Dermatologic Diseases and Disorders", [14, 22, 65, 109, 140, 142, 262]),
    ("Diabetes Mellitus", [47, 63, 165, 208, 257, 291, 314]),
    ("Diseases and Disorders of the Foot", [84, 147, 198, 241, 300]),
    ("Dizziness", [80, 99, 161, 187, 228, 243, 287]),
    ("Eating and Feeding Problems", [61, 120]),
    ("Endocrine and Metabolic Disorders", [35, 43, 105, 263, 282, 326]),
    ("Falls", [11, 41, 132, 148, 238, 240, 281, 324]),
    ("Finance", [12, 17, 36, 76, 89, 141, 176, 239, 248]),
    ("Frailty", [11, 54, 60, 98, 324]),
    ("Gait Impairment", [79, 115, 139, 152, 219]),
    ("Gastrointestinal Diseases and Disorders", [101, 155, 183, 209, 284]),
    ("Gynecologic Diseases and Disorders", [33, 38, 104, 145, 197, 322]),
    ("Hearing Impairment", [15, 23, 74, 102, 153, 200]),
    ("Heart Failure", [100, 106, 169, 227, 276, 289]),
    ("Hematologic Diseases and Disorders", [10, 86, 90, 112, 131, 224, 274, 296]),
    ("Hospital Care", [6, 40, 49, 88, 139, 144, 158, 250, 281]),
    ("Hypertension", [100, 122, 129, 316, 328]),
    ("Infectious Diseases", [56, 93, 123, 144, 222, 231, 295]),
    ("Kidney Diseases", [31, 71, 210, 264, 310, 323]),
    ("Legal and Ethical Issues", [5, 59, 157, 212, 218, 223, 234, 251, 268, 312, 319]),
    ("Malnutrition", [2, 26, 69, 207, 282, 332]),
    ("Mental Retardation and Developmental Disabilities", [75, 195, 312, 320]),
    ("Mistreatment of Older Adults", [5, 202, 255, 319]),
    ("Multimorbidity", [71, 259, 307]),
    ("Neurologic Diseases and Disorders", [70, 162, 167, 180, 191, 194, 204, 294]),
    ("Nursing-Home Care", [51, 89, 172, 175, 231, 261]),
    ("Oncology", [46, 174, 206, 211, 271, 277]),
    ("Oral Diseases and Disorders", [160, 215, 216, 229, 262, 329]),
    ("Osteoporosis", [29, 83, 159, 163, 168, 290, 298, 311, 331]),
    ("Outpatient Care Systems", [91, 119, 124, 275]),
    ("Palliative Care", [17, 30, 52, 81, 121, 128, 137, 150, 230, 315]),
    ("Perioperative Care", [1, 32, 213, 258, 259, 321]),
    ("Persistent Pain", [66, 107, 116, 253, 283, 291, 333]),
    ("Personality and Somatoform Disorders", [67, 188, 232, 304, 306]),
    ("Pharmacotherapy", [8, 57, 70, 78, 127, 130, 134, 172, 203, 311]),
    ("Physical Activity", [19, 54, 149, 225, 285, 318]),
    ("Pressure Ulcers and Wound Care", [34, 44, 92, 137, 199, 330]),
    ("Prevention", [55, 96, 186, 220, 221]),
    ("Prostate Disease", [135, 170, 177, 185, 206, 271]),
    ("Psychotic Disorders", [85, 235, 242, 299]),
    ("Rehabilitation", [61, 191, 193, 204]),
    ("Respiratory Diseases and Disorders", [6, 27, 94, 111, 118, 267]),
    ("Sexual Function Disorders", [38, 45, 73, 146]),
    ("Sleep Problems", [21, 111, 184, 192, 201, 308]),
    ("Syncope", [50, 87, 113, 162, 194, 252]),
    ("Transitional Care", [7, 64, 292]),
    ("Urinary Incontinence", [133, 164, 181, 203, 250, 288]),
    ("Visual Impairment", [126, 151, 171, 260, 280, 314]),
    ("Musculoskeletal Diseases and Disorders", [16, 42, 66, 233, 258, 297]),
    # Virtual sub-chapters carved from broader GRS8 buckets so every IMA
    # syllabus topic has at least one direct GRS8 anchor. Pages reuse the
    # parent Neurologic / Cardiovascular page ranges.
    ("Parkinson Disease", [70, 162, 167, 191, 204]),
    ("Cardiac Arrhythmias", [3, 95, 108, 114, 236]),
    ("Sarcopenia and Muscle Loss", [54, 60, 98]),
    ("Hypothermia and Thermoregulation", [263, 282, 326]),
]

# 42 IMA syllabus topics from Geriatrics2024version3forpublication.pdf
IMA_TOPICS = [
    "Alzheimer and other Dementias",
    "Andropausa",
    "Anemias",
    "Arrhythmia",
    "Auditory and visual issues",
    "Biology of aging",
    "Confusional states/ Delirium",
    "Congestive heart failure",
    "Constipation",
    "Comprehensive geriatric assessment",
    "Dementia and cognitive impairment",
    "Demography of aging",
    "Depression",
    "Diabetes",
    "Dysphagia",
    "End of life care",
    "Ethics",
    "Falls",
    "Fractures",
    "Frailty",
    "Geriatrics in Israel – local aspects",
    "Hypertension",
    "Hypothermia",
    "Incontinence – urinary and fecal",
    "Infections in the elderly",
    "Ischemic heart disease – peripheral vascular disease",
    "Nutrition and enteral feeding",
    "Osteoarthritis, Osteoporosis",
    "Parkinson’s disease and Extrapyramidal syndrome",
    "Physical activity and exercise",
    "Postural instability",
    "Pressure sores",
    "Prevention and health promotion",
    "Problems of polypharmacy",
    "Pulmonary embolism",
    "Quality of life",
    "Rehabilitation",
    "Sarcopenia",
    "Sensory deprivation",
    "Stroke and related disorders",
    "The geriatric team – team-work",
    "Urinary tract infection – renal failure",
]

GRS8_TO_IMA = {
    "Adverse Drug Events": "Problems of polypharmacy",
    "Anxiety Disorders": "Depression",
    "Assessment": "Comprehensive geriatric assessment",
    "Back and Neck Pain": "Osteoarthritis, Osteoporosis",
    "Behavior Problems in Dementia": "Dementia and cognitive impairment",
    "Biology": "Biology of aging",
    "Cardiovascular Diseases and Disorders": "Ischemic heart disease – peripheral vascular disease",
    "Community-Based Care": "Geriatrics in Israel – local aspects",
    "Complementary and Alternative Medicine": "Quality of life",
    "Cultural Aspects of Care": "Geriatrics in Israel – local aspects",
    "Delirium": "Confusional states/ Delirium",
    "Dementia": "Alzheimer and other Dementias",
    "Demography": "Demography of aging",
    "Depression and Other Mood Disorders": "Depression",
    "Dermatologic Diseases and Disorders": "Pressure sores",
    "Diabetes Mellitus": "Diabetes",
    "Diseases and Disorders of the Foot": "Postural instability",
    "Dizziness": "Postural instability",
    "Eating and Feeding Problems": "Nutrition and enteral feeding",
    "Endocrine and Metabolic Disorders": "Diabetes",
    "Falls": "Falls",
    "Finance": "Geriatrics in Israel – local aspects",
    "Frailty": "Frailty",
    "Gait Impairment": "Postural instability",
    "Gastrointestinal Diseases and Disorders": "Constipation",
    "Gynecologic Diseases and Disorders": "Andropausa",
    "Hearing Impairment": "Auditory and visual issues",
    "Heart Failure": "Congestive heart failure",
    "Hematologic Diseases and Disorders": "Anemias",
    "Hospital Care": "The geriatric team – team-work",
    "Hypertension": "Hypertension",
    "Infectious Diseases": "Infections in the elderly",
    "Kidney Diseases": "Urinary tract infection – renal failure",
    "Legal and Ethical Issues": "Ethics",
    "Malnutrition": "Nutrition and enteral feeding",
    "Mental Retardation and Developmental Disabilities": "Quality of life",
    "Mistreatment of Older Adults": "Ethics",
    "Multimorbidity": "Comprehensive geriatric assessment",
    "Neurologic Diseases and Disorders": "Stroke and related disorders",
    "Nursing-Home Care": "Geriatrics in Israel – local aspects",
    "Oncology": "Quality of life",
    "Oral Diseases and Disorders": "Dysphagia",
    "Osteoporosis": "Osteoarthritis, Osteoporosis",
    "Outpatient Care Systems": "The geriatric team – team-work",
    "Palliative Care": "End of life care",
    "Perioperative Care": "Fractures",
    "Persistent Pain": "End of life care",
    "Personality and Somatoform Disorders": "Depression",
    "Pharmacotherapy": "Problems of polypharmacy",
    "Physical Activity": "Physical activity and exercise",
    "Pressure Ulcers and Wound Care": "Pressure sores",
    "Prevention": "Prevention and health promotion",
    "Prostate Disease": "Andropausa",
    "Psychotic Disorders": "Depression",
    "Rehabilitation": "Rehabilitation",
    "Respiratory Diseases and Disorders": "Pulmonary embolism",
    "Sexual Function Disorders": "Andropausa",
    "Sleep Problems": "Quality of life",
    "Syncope": "Postural instability",
    "Transitional Care": "The geriatric team – team-work",
    "Urinary Incontinence": "Incontinence – urinary and fecal",
    "Visual Impairment": "Sensory deprivation",
    "Musculoskeletal Diseases and Disorders": "Osteoarthritis, Osteoporosis",
    "Parkinson Disease": "Parkinson’s disease and Extrapyramidal syndrome",
    "Cardiac Arrhythmias": "Arrhythmia",
    "Sarcopenia and Muscle Loss": "Sarcopenia",
    "Hypothermia and Thermoregulation": "Hypothermia",
}

GRS8_HE = {
    "Adverse Drug Events": "תופעות לוואי תרופתיות",
    "Anxiety Disorders": "הפרעות חרדה",
    "Assessment": "הערכה גריאטרית",
    "Back and Neck Pain": "כאבי גב וצוואר",
    "Behavior Problems in Dementia": "הפרעות התנהגות בדמנציה",
    "Biology": "ביולוגיה של ההזדקנות",
    "Cardiovascular Diseases and Disorders": "מחלות לב וכלי דם",
    "Community-Based Care": "טיפול קהילתי",
    "Complementary and Alternative Medicine": "רפואה משלימה",
    "Cultural Aspects of Care": "היבטים תרבותיים בטיפול",
    "Delirium": "דליריום",
    "Dementia": "דמנציה",
    "Demography": "דמוגרפיה של הזיקנה",
    "Depression and Other Mood Disorders": "דיכאון והפרעות מצב רוח",
    "Dermatologic Diseases and Disorders": "מחלות עור",
    "Diabetes Mellitus": "סוכרת",
    "Diseases and Disorders of the Foot": "מחלות כף הרגל",
    "Dizziness": "סחרחורת",
    "Eating and Feeding Problems": "בעיות אכילה והאכלה",
    "Endocrine and Metabolic Disorders": "מחלות אנדוקריניות ומטבוליות",
    "Falls": "נפילות",
    "Finance": "היבטים פיננסיים",
    "Frailty": "שברירות",
    "Gait Impairment": "הפרעות הליכה",
    "Gastrointestinal Diseases and Disorders": "מחלות מערכת העיכול",
    "Gynecologic Diseases and Disorders": "מחלות גינקולוגיות",
    "Hearing Impairment": "ליקוי שמיעה",
    "Heart Failure": "אי-ספיקת לב",
    "Hematologic Diseases and Disorders": "מחלות המטולוגיות",
    "Hospital Care": "אשפוז וטיפול בבית-חולים",
    "Hypertension": "יתר לחץ דם",
    "Infectious Diseases": "מחלות זיהומיות",
    "Kidney Diseases": "מחלות כליה",
    "Legal and Ethical Issues": "סוגיות משפטיות ואתיות",
    "Malnutrition": "תת-תזונה",
    "Mental Retardation and Developmental Disabilities": "פיגור שכלי ומוגבלויות התפתחותיות",
    "Mistreatment of Older Adults": "התעללות בקשישים",
    "Multimorbidity": "ריבוי מחלות",
    "Neurologic Diseases and Disorders": "מחלות נוירולוגיות",
    "Nursing-Home Care": "טיפול במוסד סיעודי",
    "Oncology": "אונקולוגיה",
    "Oral Diseases and Disorders": "מחלות חלל הפה",
    "Osteoporosis": "אוסטאופורוזיס",
    "Outpatient Care Systems": "מרפאות חוץ",
    "Palliative Care": "טיפול פליאטיבי",
    "Perioperative Care": "טיפול פריאופרטיבי",
    "Persistent Pain": "כאב כרוני",
    "Personality and Somatoform Disorders": "הפרעות אישיות וסומטופורמיות",
    "Pharmacotherapy": "פרמקותרפיה",
    "Physical Activity": "פעילות גופנית",
    "Pressure Ulcers and Wound Care": "פצעי לחץ וטיפול בפצעים",
    "Prevention": "מניעה",
    "Prostate Disease": "מחלות הערמונית",
    "Psychotic Disorders": "הפרעות פסיכוטיות",
    "Rehabilitation": "שיקום",
    "Respiratory Diseases and Disorders": "מחלות מערכת הנשימה",
    "Sexual Function Disorders": "הפרעות בתפקוד מיני",
    "Sleep Problems": "בעיות שינה",
    "Syncope": "סינקופה",
    "Transitional Care": "טיפול מעברי",
    "Urinary Incontinence": "אי-נקיטת שתן",
    "Visual Impairment": "ליקוי ראייה",
    "Musculoskeletal Diseases and Disorders": "מחלות שלד-שריר",
    "Parkinson Disease": "מחלת פרקינסון",
    "Cardiac Arrhythmias": "הפרעות קצב לב",
    "Sarcopenia and Muscle Loss": "סרקופניה ואיבוד מסת שריר",
    "Hypothermia and Thermoregulation": "היפותרמיה וויסות חום",
}

# GRS8 topic -> ti index from data/topics.json (0..46)
GRS8_TI = {
    "Adverse Drug Events": [8],
    "Anxiety Disorders": [7],
    "Assessment": [2],
    "Back and Neck Pain": [14, 16],
    "Behavior Problems in Dementia": [6],
    "Biology": [0],
    "Cardiovascular Diseases and Disorders": [17],
    "Community-Based Care": [35],
    "Complementary and Alternative Medicine": [8],
    "Cultural Aspects of Care": [33],
    "Delirium": [5],
    "Dementia": [6],
    "Demography": [1],
    "Depression and Other Mood Disorders": [7],
    "Dermatologic Diseases and Disorders": [10],
    "Diabetes Mellitus": [22],
    "Diseases and Disorders of the Foot": [4],
    "Dizziness": [4, 39],
    "Eating and Feeding Problems": [9, 42],
    "Endocrine and Metabolic Disorders": [22, 23],
    "Falls": [4],
    "Finance": [33, 35],
    "Frailty": [3],
    "Gait Impairment": [4, 36],
    "Gastrointestinal Diseases and Disorders": [12],
    "Gynecologic Diseases and Disorders": [43],
    "Hearing Impairment": [37],
    "Heart Failure": [18],
    "Hematologic Diseases and Disorders": [25],
    "Hospital Care": [38, 45],
    "Hypertension": [19],
    "Infectious Diseases": [27],
    "Kidney Diseases": [24],
    "Legal and Ethical Issues": [29, 33],
    "Malnutrition": [9],
    "Mental Retardation and Developmental Disabilities": [33],
    "Mistreatment of Older Adults": [30],
    "Multimorbidity": [2],
    "Neurologic Diseases and Disorders": [20, 40],
    "Nursing-Home Care": [35],
    "Oncology": [26],
    "Oral Diseases and Disorders": [42],
    "Osteoporosis": [15],
    "Outpatient Care Systems": [35, 45],
    "Palliative Care": [28, 34],
    "Perioperative Care": [38],
    "Persistent Pain": [14],
    "Personality and Somatoform Disorders": [7],
    "Pharmacotherapy": [8],
    "Physical Activity": [3, 36],
    "Pressure Ulcers and Wound Care": [10],
    "Prevention": [44],
    "Prostate Disease": [11, 26, 43],
    "Psychotic Disorders": [7, 6],
    "Rehabilitation": [36],
    "Respiratory Diseases and Disorders": [21],
    "Sexual Function Disorders": [43],
    "Sleep Problems": [13],
    "Syncope": [4, 18, 39],
    "Transitional Care": [35, 45],
    "Urinary Incontinence": [11],
    "Visual Impairment": [37],
    "Musculoskeletal Diseases and Disorders": [16, 15],
    "Parkinson Disease": [40],
    "Cardiac Arrhythmias": [41],
    "Sarcopenia and Muscle Loss": [3],
    "Hypothermia and Thermoregulation": [39],
}

entries = {}
for idx, (topic, qs) in enumerate(GRS8_TOPICS, start=1):
    pages_for_qs = [Q_PAGES[q] for q in qs if q in Q_PAGES]
    if not pages_for_qs:
        first_page, last_page = 13, 13
    else:
        first_page, last_page = min(pages_for_qs), max(pages_for_qs)
    sl = GRS8_TO_IMA.get(topic)
    if sl is not None and sl not in IMA_TOPICS:
        print(f'WARN: {topic} -> {sl} not in IMA list', file=sys.stderr)
        sl = None
    entry = {
        "id": f"grs8-ch{idx:02d}",
        "title": topic,
        "title_he": GRS8_HE.get(topic, ""),
        "part": "grs8_part01.pdf",
        "pages": [first_page, last_page],
        "ti": GRS8_TI.get(topic, []),
        "syllabus_topic": sl,
        "questions": qs,
    }
    entries[str(idx)] = entry

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, 'w', encoding='utf-8') as f:
    json.dump(entries, f, ensure_ascii=False, indent=2)
print(f"Wrote {len(entries)} chapters -> {OUT}")

mapped_ima = set(e['syllabus_topic'] for e in entries.values() if e['syllabus_topic'])
print(f"IMA coverage: {len(mapped_ima)}/{len(IMA_TOPICS)} topics mapped")
unmapped_ima = [t for t in IMA_TOPICS if t not in mapped_ima]
if unmapped_ima:
    print("UNMAPPED IMA topics:")
    for t in unmapped_ima:
        print(f"  - {t}")
else:
    print("All IMA topics covered.")
