/* strip-thinking-preamble@v1
   The extractor named in every direct-fetch source record. Until this file existed, that name
   pointed at nothing: the function lived only as inline JavaScript typed into the page, so a
   record could name an extractor nobody could inspect or re-run. A named-but-unavailable
   extractor is a citation to a source that does not exist - the same shape as a digest over a
   vanished object, one level up. Committed so the name resolves.

   WHAT IT DOES. A lane message rendered in the app carries the client's thinking-summary lines
   above the body, repeated an unstable number of times as the UI settles. Hashing the raw node
   therefore produced different digests for the same unchanged message (measured: 2900 then 2794).
   This drops the duplicated preamble and returns the body.

   WHAT IT CANNOT DO, and this matters for the capture already in the repo: it takes the RENDERED
   NODE as input. That object is windowed - a message was gone from the page 2m08s after it was
   hashed - so an existing capture CANNOT be regenerated by re-running this. Committing the code
   makes the extractor inspectable and re-runnable on FUTURE fetches. It does not retroactively
   prove that this code produced any capture already on disk. What supports that capture is the
   digest match at transfer time and, more strongly, the chat lane's own independent read of the
   file against what it actually wrote.

   Determinism was demonstrated only across reads 1.2 seconds apart. The minutes-apart test could
   not be run, because the object does not survive that long. That question stays open and is not
   closed by this file. It stopped mattering for AUDITABILITY once the text was persisted - the
   capture is fixed - but it still matters for whether two fetches of the same live message agree. */

export function stripThinkingPreamble(nodeText) {
  const lines = nodeText.split('\n');
  const seen = new Set();
  let start = 0;
  for (let i = 0; i < lines.length; i++) {
    const k = lines[i].trim().replace(/\.$/, '');
    if (!k) continue;
    if (seen.has(k)) { start = i + 1; seen.add(k); continue; }
    if (seen.size === 0) { seen.add(k); start = i; continue; }
    start = i; break;
  }
  return lines.slice(start).join('\n').trim();
}

export const VERSION = 'strip-thinking-preamble@v1';
